favicon: null
name: jonmok
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.218638
  brandStrength: 0.5035842
  lightness: 0
  brandColors:
    - '#CECDCB'
    - '#100E11'
    - '#5D4137'
    - '#A39D9D'
    - '#817272'
  rhythmicContrast: 0.2903226
typography_spectrum: 0.1290025585331023
layout_spectrum: 0.6218086644075811
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
