analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.6218086644075811
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.3038747089449316
  brandStrength: 0.00146227958612144
  rhythmicContrast: 0.7065570834092796
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0.1715197537560016
purpose: []
favicon: null
name: jonmok
typography_spectrum: 0.1290025585331023
